<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-17 12:06
=======
# Generated by Django 4.2.3 on 2023-07-18 11:37
>>>>>>> d7caeb229884e831d99fd1917b634cdd7a31c8f1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=65)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
