# Generated by Django 4.2.3 on 2023-07-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('author', '0002_authormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='category',
        ),
        migrations.AlterModelTable(
            name='authormodel',
            table='author',
        ),
        migrations.AddField(
            model_name='authormodel',
            name='category',
            field=models.ManyToManyField(null=True, to='category.categorymodel'),
        ),
    ]
