# Generated by Django 4.2.3 on 2023-07-17 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_authormodel_user_remove_authormodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/author'),
            preserve_default=False,
        ),
    ]
