# Generated by Django 4.2.3 on 2023-07-17 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/book'),
            preserve_default=False,
        ),
    ]
